### ISSUE TITLE
equalGridCrossing doesn't change the community set to person object

### ISSUE THREAD

**Issue by ManuMBhat** [ManuMBhat/py-pandemic#4]
In equalGridCrossing function(Base.py, City class) the person objects are not modified by changing the community they now belong to. This could have affect on other functions. Unless this is necessary for some other function. In which case we might need to re do that function as well

**Comment by pronei** [comment]
I haven't changed the `community` attribute for `Person` objects when they're displaced from their original `Community` as there's a possibility of them to return back. Currently no function utilizes this membership attribute so you can relabel this issue as possible enhancement.

Support for a modified form of `equalGridCrossing` that allows the client to specify whether individuals are permanently or temporarily displaced could be implemented. For those temporarily displaced, implementing a `returnTravelers()` method that undoes all such displacements within a `City` should be added.

**Comment by ManuMBhat** [comment]
Oh,ok. That makes sense.
